export const INITIALISE_QUIZ_ATTEMPT = "INITIALISE_QUIZ_ATTEMPT";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const INCREMENT_QUESTION_NUMBER = "INCREMENT_QUESTION_NUMBER";
export const RESET_QUIZ = "RESET_QUIZ";
export const SELECT_OPTION = "SELECT_OPTION";
export const SHOW_RESULT = "SHOW_RESULT";
