const INITIALISE_QUIZ_ATTEMPT = "INITIALISE_QUIZ_ATTEMPT";
const UPDATE_SCORE = "UPDATE_SCORE";
const INCREMENT_QUESTION_NUMBER = "INCREMENT_QUESTION_NUMBER";
const RESET_QUIZ = "RESET_QUIZ";
const SELECT_OPTION = "SELECT_OPTION";

export {
  INITIALISE_QUIZ_ATTEMPT,
  INCREMENT_QUESTION_NUMBER,
  UPDATE_SCORE,
  RESET_QUIZ,
  SELECT_OPTION,
};
